spring:
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    open-in-view: false
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: d226d405-0d4c-4de5-b078-5535f13e7952
  expiration: 999999